[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[build.environment]
  NODE_ENV = "production"
  DISABLE_ESLINT_PLUGIN = "true"
